# -*- coding: utf-8 -*-
"""session-5-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-sA23UWiCf3NoQfT6fiTnxZORVUQ_DH

# Tuple

###`Q1:` Join Tuples if similar initial element
While working with Python tuples, we can have a problem 
in which we need to perform concatenation of records from 
the similarity of initial element. This problem can have 
applications in data domains such as Data Science.

For eg.
```
Input  : test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]
Output : [(5, 6, 7, 8), (6, 10), (7, 13)]
```
"""
def tupq1():
    test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13),(5, 18),(6,166)]
    result = []
    for i in test_list:
        if len(result) == 0 :
            result.append(list(i))
        else:
            for j in result:
                counter = 0
                if j[0] == i[0] :
                    j.append(i[1])
                    break
                else :
                    counter = 1
            if counter == 1 :
                result.append(list(i))
    for k in range(len(result)) :
        result[k] = tuple(result[k])
    print(result)       

def tupq1_s2():
    test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13),(5, 18),(6,166)]
    initial = []
    init=[]

    for i in test_list:
        if i[0] not in init :
            init.append(i[0])
            initial.append([i[0]])

    for i in test_list:
        for j in initial :
            if i[0] == j[0] :
                break
        j.append(i[1])

    for i in range(len(initial)) :
        initial[i] = tuple(initial[i])
    print(initial)
         

def tupq1_s3():
    test_list = [(5, 6), (5, 7), (5, 8), (6, 10), (7, 13)]

    unique = []

    for i in test_list:
        unique.append(i[0])
    unique = set(unique)

    result = []
    for i in unique:
        result.append([i])
        for j in test_list:
            if j[0] == i:
                result[-1].append(j[1])

    print(list(map(tuple,result)))
# write your code here

"""###`Q2:` Multiply Adjacent elements (both side) and take sum of right and left side multiplication result.


For eg.
```
The original tuple : (1, 5, 7, 8, 10)
Resultant tuple after multiplication :

(1*5, 1*5+5*7, 7*5 + 7*8, 8*7 + 8*10, 10*8) -> (5, 40, 91, 136, 80)

output-(5, 40, 91, 136, 80)
```
"""
def tupq2():
    tup1 = (1, 5, 7, 8, 10)
    n = len(tup1)
    result = []
    result.append(tup1[0]*tup1[1])

    for i in range(1,n-1):
        result.append(tup1[i]*tup1[i-1] + tup1[i]*tup1[i+1])

    result.append(tup1[-1] * tup1[-2])
    result = tuple(result)
    print(result)

# write your code here

"""###`Q3`: Check if tuples are same or not?
Two tuples would be same if both tuples have same element at same index
```
t1 = (1,2,3,0)
t2 = (0,1,2,3)

t1 and t2 are not same
```
"""

def tupq3():
    t1 = (1,2,3,0)
    t2 = (1,2,3,0)
    t3 = tuple(zip(t1,t2))
    counter = 0
    for i,j in t3 :
        if i != j :
            counter += 1
            break
    if counter != 0:
        print("Not The same")
    else :
        print("Same")

# write your code here

"""###`Q4`: Count no of tuples, list and set from a list
```
list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]

```
`Output:`

```
List-2
Set-2
Tuples-1
```
"""

def tupq4():
    list1 = [{'hi', 'bye'},{'Geeks', 'forGeeks'},('a', 'b'),['hi', 'bye'],['a', 'b']]
    List = 0
    Tuples = 0
    Set = 0
    for i in list1 :
        if type(i) == list :
            List += 1
        elif type(i) == tuple:
            Tuples +=1 
        elif type(i) == set:
            Set += 1

    print(List, 
          Tuples,
          Set)
            

# write your code here

"""###`Q5`: Shortlist Students for a Job role
Ask user to input students record and store in tuples for each record. Then Ask user to input three things he wants in the candidate- Primary Skill, Higher Education, Year of Graduation.

Show every students record in form of tuples if matches all required criteria.

It is assumed that there will be only one primry skill.

If no such candidate found, print `No such candidate`

`Input:`
```
Enter No of records- 2
Enter Details of student-1
Enter Student name- Manohar
Enter Higher Education- B.Tech
Enter Primary Skill- Python
Enter Year of Graduation- 2022
Enter Details of student-2
Enter Student name- Ponian
Enter Higher Education- B.Sc.
Enter Primary Skill- C++
Enter Year of Graduation- 2020

Enter Job Role Requirement
Enter Skill- Python
Enter Higher Education- B.Tech
Enter Year of Graduation- 2022
```

`Output`
```
('Manohar', 'B.tech', 'Python', '2022')
```

"""
def tupq5():
    n = int(input("Enter no. of student records : "))
    records = []

    print("Enter Job Role Requirement - ")
    ps = input("Enter Skill: ")
    he = input("Enter Higher Education: ")
    yog = input("Enter Year of Graduation: ")

    for i in range(1,n+1):
        print("Enter records of student-",i)
        name = input("Enter Student name: ")
        HE = input("Enter Higher Education: ")
        PS = input("Enter Primary Skill: ")
        YOG = input("Enter Year of Graduation: ")

        
        if HE == he and PS == ps and YOG == yog :
            records.append((name,HE,PS,YOG))

    if len(records) == 0:
        print("NO SUCH CANDIDATE")
    else :
        for i in records :
            print(i)

def tupq5_s2():
    students = []
    num = int(input('enter the number of applicants'))

    for i in range(num):
        print('Enter details of',i+1,'applicant:')
        name = input('enter name')
        h_ed = input('enter higher education')
        p_skill = input('enter primary skill')
        yog = input('enter year of graduation')

        students.append((name,h_ed,p_skill,yog))

    required_skill = input('enter required skill')
    required_hed = input('enter required higher education')
    required_yog = input('enter required year of graduation')

    flag = False
    for i in students:
        if i[1] == required_hed and i[2] == required_skill and i[3] == required_yog:
            print(i)
            flag = True

    if flag == False:
        print('No such candidates')
# write your code here

"""# Set

###`Q1:` Write a program to find set of common elements in three lists using sets.
```
Input : ar1 = [1, 5, 10, 20, 40, 80]
        ar2 = [6, 7, 20, 80, 100]
        ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

Output : [80, 20]
```
"""
def setq1():
    ar1 = [1, 5, 10, 20, 40, 80]
    ar2 = [6, 7, 20, 80, 100]
    ar3 = [3, 4, 15, 20, 30, 70, 80, 120]

    sar1 = set(ar1)
    sar2 = set(ar2)
    sar3 = set(ar3)

    result = sar1.intersection(sar2.intersection(sar3))
    print(list(result))


# write your code here

"""###`Q2:` Write a program to count unique number of vowels using sets in a given string. Lowercase and upercase vowels will be taken as different.

`Input:`
```
Str1 = "hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX"
```
`Output:`
```
No of unique vowels-6
```
"""
def setq2():
    Str1 = set("hands-on data science mentorship progrAm with live classes at affordable fee only on CampusX")    
    vowel = set('aeiouAEIOU')

    an = Str1 & vowel
    
    
    # for i in Str1:
    #     if i in 'aeiouAEIOU':
    #         vowel.add(i)
    print("No. of unique vowel -",len(an))



# write your code here

"""### `Q3:` Write a program to Check if a given string is binary string of or not.

A string is said to be binary if it's consists of only two unique characters.

Take string input from user.

```
Input: str = "01010101010"
Output: Yes

Input: str = "1222211"
Output: Yes

Input: str = "Campusx"
Output: No
```
"""
def setq3():
    string = set(input("Enter string: "))
    if len(string) == 2 :
        print("Binary")
    else :
        print("No")


# write your code here

"""### `Q4`: find union of n arrays.

**Example 1:**

Input:
```bash
[[1, 2, 2, 4, 3, 6],
 [5, 1, 3, 4],
 [9, 5, 7, 1],
 [2, 4, 1, 3]]
```

Output:

```bash
[1, 2, 3, 4, 5, 6, 7, 9]
```
"""

def setq4():
    arrays = [[1, 2, 2, 4, 3, 6],
              [5, 1, 3, 4],
              [9, 5, 7, 1],
              [2, 4, 1, 3]]
    s1 = set()
    for i in arrays :
        s1.update(i)
    print(s1)

# write your code here

"""### `Q5`: Intersection of two lists. Intersection of two list means we need to take all those elements 
which are common to both of the initial lists and store them into another list. 
Only use using **list-comprehension**.

**Example 1:**

Input:
```bash
lst1 = {15, 9, 10, 56, 23, 78, 5, 4, 9}
lst2 = {9, 4, 5, 36, 47, 26, 10, 45, 87}
```

Output:
```bash
[9, 10, 4, 5]
```

**Example 2:**

Input:
```bash
lst1 = {4, 9, 1, 17, 11, 26, 28, 54, 69}
lst2 = {9, 9, 74, 21, 45, 11, 63, 28, 26}
```

Output:
```bash
[9, 11, 26, 28]
```
"""

def setq5():
    lst1 = [4, 9, 1, 17, 11, 26, 28, 54, 69]
    lst2 = [9, 9, 74, 21, 45, 11, 63, 28, 26]

    lst3 = [i for i in lst1 if i in lst2]
    # lst3.extend(set(lst1) & set(lst2))
    print(lst3)

# write your code here

"""# Dictionary

### `Q1`: Key with maximum unique values

Given a dictionary with values list, extract key whose value has most unique values.

**Example 1:**

Input:

```bash
test_dict = {"CampusX" : [5, 7, 9, 4, 0], "is" : [6, 7, 4, 3, 3], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
CampusX
```

**Example 2:**

Input:
```bash
test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}
```

Output:
```bash
Best
```
"""

def dcq1():
    test_dict = {"CampusX" : [5, 7, 7, 7, 7], "is" : [6, 7, 7, 7], "Best" : [9, 9, 6, 5, 5]}    
    max = 0
    high = None
    for key in test_dict:
        if max < len(set(test_dict[key])):
            max = len(set(test_dict[key]))
            high = key
    print(high)

# write your code here 

"""### `Q2`: Replace words from Dictionary. Given String, replace it's words from lookup dictionary.

**Example 1:**

Input:

```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}
```

Output:

```bash
CampusX is the best channel for Data-Science students.
```

**Example 2:**

Input:
```bash
test_str = 'CampusX best for DS students.'
repl_dict = {"good" : "is the best channel", "ds" : "Data-Science"}
```

Output:
```bash
CampusX best for DS students.
```
"""

def dcq2():
    test_str = 'CampusX best for DS students.'.split()
    repl_dict = {"best" : "is the best channel", "DS" : "Data-Science"}

    for i in test_str :
        if i in repl_dict:
            test_str[test_str.index(i)] = repl_dict[i]
    
    result = " ".join(test_str)
    print(result)


# write your code here

"""### `Q3`: Convert List to List of dictionaries. Given list values and keys list, 
convert these values to key value pairs in form of list of dictionaries.

**Example 1:**

Input:
```bash
test_list = ["DataScience", 3, "is", 8]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'DataScience', 'id': 3}, {'name': 'is', 'id': 8}]
```

**Example 2:**

Input:
```bash
test_list = ["CampusX", 10]
key_list = ["name", "id"]
```

Output:

```bash
[{'name': 'CampusX', 'id': 10}]
```
"""

def dcq3():
    test_list = ["CampusX", 10,"Prasham",21,"is",8]
    key_list = ["name", "id"]
    list1 = []

    k = len(key_list)
    v = len(test_list)
    for i in range(0,v,k):
        list1.append(dict(zip(key_list,test_list[:k])))
        test_list= test_list[k:]
    print(list1)

# write your code here

"""### `Q4`: Convert a list of Tuples into Dictionary.

**Example 1:**

Input:
```bash
[("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
```

Output:
```bash
{'akash': [10], 'gaurav': [12], 'anand': [14], 'suraj': [20], 'akhil': [25], 'ashish': [30]}
```

**Example 2:**

Input:
```bash
[('A', 1), ('B', 2), ('C', 3)]
```

Output:
```bash
{'A': [1], 'B': [2], 'C': [3]}
```
"""

def dcq4():
    list1 = [("akash", 10), ("gaurav", 12), ("anand", 14), ("suraj", 20), ("akhil", 25), ("ashish", 30)]
    dic = {}
    for i,j in list1 :
        dic[i] = [j]
    print(dic)
dcq4()
# write your code here

"""### `Q5`: Sort Dictionary key and values List.

**Example 1:**

Input:

```bash
{'c': [3], 'b': [12, 10], 'a': [19, 4]}
```

Output:

```bash
{'a': [4, 19], 'b': [10, 12], 'c': [3]}
```

**Example 2:**

Input:

```bash
{'c': [10, 34, 3]}
```

Output:

```bash
{'c': [3, 10, 34]}
```
"""
def dcq5():
    d1 = {'c': [3], 'b': [12, 10], 'a': [19, 4]}

    # k = d1.keys()
    # v = d1.values()
    # l1 = sorted(list(zip(k,v)))
    # d2 = {}
    # for i,j in l1 :
    #     d2[i] = sorted(j)
    # print(d2)

    res = {}

    for i in sorted(d1):
        res[i] = sorted(d1[i])

    print(res)



# write your code here