# -*- coding: utf-8 -*-
"""session-4-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yS_YGxipe9H30u0RZLqAnMNjHsq102HD

###`Problem 1:` Combine two lists index-wise(columns wise)
Write a program to add two lists index-wise. Create a new 
list that contains the 0th index item from both the list, 
then the 1st index item, and so on till the last element.
any leftover items will get added at the end of the new 
list.
`Given List:`
```
list1 = ["M", "na", "i", "Kh"]
list2 = ["y", "me", "s", "an"]
```

`Output:`
```
[['M','y'], ['na', me'], ['i', 's'], ['Kh', 'an']]
```
"""
def q1():
  list1 = ["M", "na", "i", "Kh"]
  list2 = ["y", "me", "s", "an","hel","okay"]
  list3 = list(zip(list1,list2))
  n = len(list3)
  for i in range(n) :
    list3[i]=list(list3[i])
  if len(list1) > len(list2):
    list3.extend(list1[n:])
  else:
    list3.extend(list2[n:])
  print(list3)


"""### `Problem 2:` Add new item to list after a specified item
Write a program to add item 7000 after 6000 in the following Python List
```
list1 = [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
```
`Output:`
```
[10, 20, [300, 400, [5000, 6000, 7000], 500], 30, 40]
```
"""

def q2():
  list1= [10, 20, [300, 400, [5000, 6000], 500], 30, 40]
  list1[2][2].insert(2,7000)
  print(list1)

# Write code here

"""###`Problem 3:` Update no of items available

Suppose you are given a list of candy and another list of same size representing no of items of respective candy.

i.e -  
```
candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
no_of_items = [10,20,34,74,32]
```
Write a program to show no. of items of each candy type.

`Output:`

```
Jelly Belly-10
Kit Kat-20
Double Bubble-34
Milky Way-74
Three Musketeers-32

```
"""
def q3():
  candy_list = ['Jelly Belly','Kit Kat','Double Bubble','Milky Way','Three Musketeers']
  no_of_items = [10,20,34,74,32]
  list3 = list(zip(candy_list,no_of_items))
  n = len(list3)
  for i,j in list3 :
    print(f"{i}-{j}")

# Write code here

"""###`Problem 4:` Running Sum on list
Write a program to print a list after performing running sum on it.

i.e:

`Input:`
```
list1 = [1,2,3,4,5,6]
```
`Output:`
```
[1,3,6,10,15,21]
```
"""
def q4():
  list1 = [1,2,3,4,5,6]
  list2 = []
  sum = 0
  for i in range(len(list1)):
    sum += list1[i]
    list2.append(sum)

  print(list2)
# Write code here

"""###`Problem 5:` You are given a list of integers. 
You are asked to make a list by running through elements 
of the list by adding all elements greater and itself.

i.e. Say given list is `[2,4,6,10,1]`
resultant list will be `[22,20,10,23]`.

For 1st element `2` ->> these are greater `(4+6+10)` values and `2` itself so on adding becomes `22`.

For 2nd element `4` ->> greater elements are `(6, 10)` and `4` itself, so on adding `20`

like wise for all other elememts.

`[2,4,6,10,1]`-->`[22,20,16,10,23]`

"""

def q5():
  list1 = [2,4,6,10,1]
  list2 = []
  for i in list1:
    sum = 0
    for j in list1:
      if(j>=i):
        sum += j
    list2.append(sum)

  print(list2)

"""###`Problem 6:` Find list of common unique items from two list. and show in increasing order

`Input`

```
num1 = [23,45,67,78,89,34]
num2 = [34,89,55,56,39,67]
```

`Output:`
```
[34, 67, 89]
```

"""
def q6():
  num1 = [23,45,67,78,89,34]
  num2 = [34,89,55,56,39,67]

  list1 = []
  if len(num1) < len(num2):
    A = num1.copy()
    B = num2.copy()
  else :
    A = num2.copy()
    B = num1.copy()
  for i in A:
    if i in B :
      if i not in list1:
        list1.append(i)
  list1.sort()
  print(list1)

# Write code here

"""###`Problem 7:` Sort a list of alphanumeric strings based 
on product value of numeric character in it. If in any 
string there is no numeric character take it's product 
value as 1.

`Input:`
```
['1ac21', '23fg', '456', '098d','1','kls']
```

`Output:`
```
['456', '23fg', '1ac21', '1', 'kls', '098d']

```
"""

def q7():
  list1 = ['1ac21', '23fg', '456', '098d','1','kls']
  list2 = []
  for i in list1 :
    prod = 1
    for j in i :
      if j in '0123456789':
        prod *= int(j)
    list2.append([i,prod])
  list2.sort(key=lambda prod : prod[1],reverse=True)
  for i in range(len(list2)) :
    list2[i] = list2[i][0]

  print(list2)
        

"""`Problem 8:` Split String of list on K character.

**Example :**

Input:
```bash
['CampusX is a channel', 'for data-science', 'aspirants.']
```

Output:
```bash
['CampusX', 'is', 'a', 'channel', 'for', 'data-science', 'aspirants.']
```
"""

def q8():
  input_list = ['CampusX is a channel', 'for data-science', 'aspirants.']
  out_list = []
  for i in input_list :
    out_list.extend(i.split(" "))
  print(out_list)


# Write code here

"""### `Problem 9:` Convert Character Matrix to single String using string comprehension.

**Example 1:**

Input:
```bash
[['c', 'a', 'm', 'p', 'u', 'x'], ['i', 's'], ['b', 'e', 's', 't'], ['c', 'h', 'a', 'n', 'n', 'e', 'l']]
```

Output:
```bash
campux is best channel
```
"""
def q9():
  list1 = [['c', 'a', 'm', 'p', 'u', 'x'], ['i', 's'], ['b', 'e', 's', 't'], ['c', 'h', 'a', 'n', 'n', 'e', 'l']]
  list2 = [''.join(i) for i in list1]
  string = " ".join(list2)
  # for i in list1 :
  #   string += "".join(i)
  #   string += " "
  print(string)

# Write code here

"""### `Problem 10:` Add Space between Potential Words.

**Example:**

Input:

```bash
['campusxIs', 'bestFor', 'dataScientist']
```

Output:
```bash
['campusx Is', 'best For', 'data Scientist']
```
"""
def q10():
  # potential word is .title word , first letter capital . 
  list1 = ['campusxIs', 'bestFor', 'dataScientist']
  result = []
  
  for i in range(len(list1)) :
    n=-1
    for j in list1[i] :
      n+=1
      if j.isupper():
        list1[i] = list1[i][:n] + " " + list1[i][n:]
  print(list1)

def q10_2():
  test_list = ["campusxIs", "bestFor", "dataScientist"]
  result = []
  for i in test_list:
    temp_list = [[]]
    for j in i :
        if j.isupper():
            temp_list.append([]) # when we find a capital letter , then we create another list in which we append the rest of the characters
        temp_list[-1].append(j)
    for k in range(len(temp_list)):
        temp_list[k] = "".join(temp_list[k])
    result.append(" ".join(temp_list))
  print(result)


# Code here

"""### `Problem 11:` Write a program that can perform union operation on 2 lists

**Example:**

Input:

```bash
[1,2,3,4,5,1]
[2,3,5,7,8]
```

Output:
```bash
[1,2,3,4,5,7,8]
```
"""
def q11():
  list1 = [1,2,3,4,5,1]
  list2 = [2,3,5,7,8]
  list3 = list1 + list2
  result = []
  for i in list3 :
    if i not in result :
      result.append(i)
  print(result)

# Write code here

"""### `Problem 12:` Write a program that can find the max number of each row of a matrix

**Example:**

Input:

```bash
[[1,2,3],[4,5,6],[7,8,9]]
```

Output:
```bash
[3,6,9]
```
"""

def q12():
  mat = [[1,2,3],[4,5,6],[7,8,9]]
  result = []
  # for i in mat :
  #   result.append(max(i))

  result = [max(i)for i in mat]
  print(result)

# Write code here

"""### `Problem 13:` Write a list comprehension to print the following matrix

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
"""

def q13():
  result = [[0, 1, 2], [3, 4, 5], [6, 7, 8]]
  mat = [[j + 3*i for j in range(3)]for i in range(3)]
  print(mat)

# Write code here

"""### `Problem 14:` Write a list comprehension that can transpose a given matrix

matrix = [<br>
  [1,2,3],<br>
          [4,5,6],<br>
          [7,8,9]<br>]<br>

[1, 4, 7]<br>
[2, 5, 8]<br>
[3, 6, 9]<br>
"""
def q14():
  matrix = [[1,2,3],
            [4,5,6],
            [7,8,9]]
  result = [[j[i] for j in matrix]for i in range(len(matrix)) ]
  print(result)
q14()
# Write code here

"""### `Problem 15:` Write a list comprehension that can flatten a nested list

Input<br>
matrix = [<br>
  [1,2,3],<br>
          [4,5,6],<br>
          [7,8,9]<br>]<br>

Output:<br>
[1, 2, 3, 4, 5, 6, 7, 8, 9]
"""
def q15():
  matrix = [[1,2,3],
            [4,5,6],
            [7,8,9]]
  result = [j for i in matrix for j in i]
  print(result)
q15()
# Write code here