# -*- coding: utf-8 -*-
"""session-2-task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13DXTOC5mQUcVw2VAnY4xFnqIhWXfjcw2

### `Problem 1`: Write a program that will give you in hand monthly salary after deduction on CTC - HRA(10%), DA(5%), PF(3%) and taxes deduction as below:

> Salary(Lakhs) : Tax(%)

*   Below 5 : 0%
*   5-10 : 10%
*   10-20 : 20%
*   aboove 20 : 30%
"""

def q1():
    sal = int(input("Enter salary: "))
    sal_bef_tax = sal - 0.1*sal - 0.05*sal-0.03*sal
    if(sal < 500000):
        net_sal = sal_bef_tax 
    elif(sal <1000000):
        net_sal = sal_bef_tax - 0.1*sal_bef_tax
    elif(sal <=2000000):
        net_sal = sal_bef_tax - 0.2*sal_bef_tax
    else:
        net_sal = sal_bef_tax - 0.3*sal_bef_tax
    
    print(net_sal)
# Write code here

"""### `Problem 2`: Write a program that take a user input of three angles and will find out whether it can form a triangle or not."""

def q2():
    a = float(input("Enter 1st angle: "))
    b = float(input("Enter second angle: "))
    c = float(input("Enter third angle: "))

    if(a+b+c == 180.0):
        print("Triangle possible! ")
    else:
        print("Triangle not possible! ")

# Write code here

"""### `Problem 3`: Write a program that will take user input of cost price and selling price and determines whether its a loss or a profit."""

def q3():
    cp = float(input("Enter cost price: "))
    sp = float(input("Enter selling price: "))

    if(sp>cp):
        print("Profit")
    elif(sp<cp):
        print("Loss")
    else:
        print("NPNL")

# Write code here

"""### `Problem 4`: Write a menu-driven program -
1. cm to ft
2. km to miles
3. USD to INR
4. exit
"""

def q4():
    menu = int(input(""" 
Enter 1 to convert cm to ft
Enter 1 to convert km to miles
Enter 3 to convert USD to INR
Enter 4 to exit                  
"""))
    
    if(menu == 1):
        value = float(input("Enter Value to convert: "))
        ft = value*0.0328
        print(value,"cm = ",ft,"ft")
    elif(menu == 2):
        value = float(input("Enter Value to convert: "))
        miles = value *0.621371
        print(value,"km = ",miles,"miles")
    elif(menu == 3):
        value = float(input("Enter Value to convert: "))
        inr = value*95.22
        print(value,"$ = ",inr,"Rs")
    else:
        print("BYE! ")

# Write code here

"""### `Problem 5` - Exercise 12: Display Fibonacci series up to 10 terms.

*Note: The Fibonacci Sequence is a series of numbers. The next number is found by adding up the two numbers before it. The first two numbers are 0 and 1. For example, 0, 1, 1, 2, 3, 5, 8, 13, 21. The next number in this series above is 13+21 = 34*
"""
def q5():
    a = 0
    b= 1
    n = int(input("Enter no. of terms: "))
    for i in range(n):
        print(a,end=' ')
        temp = a
        a = b
        b = temp + b
    print("")



# logic - a + b , then a = b , b = sum 


# Write code here

"""### `Problem 6` - Find the factorial of a given number.

Write a program to use the loop to find the factorial of a given number.

The factorial (symbol: `!`) means to multiply all whole numbers from the chosen number down to 1.

For example: calculate the factorial of 5

```bash
5! = 5 × 4 × 3 × 2 × 1 = 120
```

Output:

```bash
120
```
"""

def q6():
    n = int(input("Enter factorial: "))
    ans = 1
    if(n != 0 and n != 1): 
        for i in range(n,1,-1):
            ans = ans*i
    print(n,"! = ",ans)

# Write code here

"""### `Problem 7` - Reverse a given integer number.

Example:

`Input:`

```bash
76542
```

`Output:`

```bash
24567
```
"""

def q7():
    num = int(input("Enter number: "))
    rev = ""
    for i in str(num):
        rev += str(num%10)
        num = num//10
    print(rev)

# logic - when num%10 --> we get units place -> the new num = num//10 -> the units place we get convert to string -> join the string at the end -> convert to integer 

# Write code here

"""### `Problem 8`: Take a user input as integer N. Find out the sum from 1 to N. If any number if divisible by 5, then skip that number. And if the sum is greater than 300, don't need to calculate the sum further more. Print the final result. And don't use for loop to solve this problem.

**Example 1:**

`Input:`

```bash
30
```

`Output:`

```bash
276
```
"""
def q8():
    n = int(input("Enter integer n: "))
    sum = 0
    a=1
    while(sum<=300 and a<=n):
        ans = sum
        if(a%5 != 0):
            sum += a
            a+=1
        else:
            a+=1
    print(ans)


# Write code here

"""### `Problem 9`: Write a program that keeps on accepting a number from the user until the user enters Zero. Display the sum and average of all the numbers."""

def q9():
    num = int(input("Enter a no. : "))
    sum = 0
    count = 1
    while (num != 0):
        sum += num
        num = int(input("Enter a no. : "))
        count += 1
    print(sum,int(sum/count))

# Write code here1

"""###`Problem 9`: Write a program which will find all such numbers which are divisible by 7 but are not a multiple of 5, between 2000 and 3200 (both included). The numbers obtained should be printed in a comma-separated sequence on a single line."""
def q9_2():
    for i in range(2000,3201):
        if(i%7==0 and i%5!=0):
            print(i,sep='',end=',')
    print("")

# Write code here

"""###`Problem 10`: Write a program, which will find all such numbers between 1000 and 3000 (both included) such that each digit of the number is an even number. The numbers obtained should be printed in a space-separated sequence on a single line.

"""
def q10():
    for i in range(1000,3001):
        num=i
        if((i%10)%2 == 0):
            i = i//10
            if((i%10)%2==0):
                i=i//10
                if((i%10)%2==0):
                    i=i//10
                    if((i%10)%2==0):
                        print(num,sep='',end=" ")
    print("\n")

# Write code here

"""###`Problem 11`: A robot moves in a plane starting from the original point (0,0). The robot can move toward UP, DOWN, LEFT and RIGHT with a given steps.
The trace of robot movement is shown as the following:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
> The numbers after the direction are steps.

> `!` means robot stop there.

**Please write a program to compute the distance from current position after a sequence of movement and original point.**

*If the distance is a float, then just print the nearest integer.*

Example:

`Input`:
```
UP 5
DOWN 3
LEFT 3
RIGHT 2
!
```
`Output`:
```
2
```
"""

def q11():
    initial_x = initial_y = 0
    x=y=0
    dir=""
    steps = 0
    while dir != "!" :
        dir = input("Enter direction - up , down , left , right or !(stop) : ")
        if dir != '!':
            steps = int(input("Enter steps moved: "))
            if dir =='up':
                y += steps
            elif dir =='down':
                y -= steps
            elif dir == 'left':
                x -= steps
            elif dir == 'right' :
                x += steps
    dist = int(((initial_x -x)**2 + (initial_y - y)**2)**0.5)    
    print("Distance travelled :",dist)

# Write code here

"""###`Problem 12`:Write a program to print whether a given number is a prime number or not"""

def q12():
    num = int(input("Enter a no. : "))
    for i in range(2,num//2+1):
        if(num%i == 0):
            count = 1
        else:
            count = 0
    if count == 0:
        print("Prime")
    else:
        print("Not prime")

# Write code here

"""###`Problem 13`:Print all the Armstrong numbers in a given range.
Range will be provided by the user<br>
Armstrong number is a number that is equal to the sum of cubes of its digits. For example 0, 1, 153, 370, 371 and 407 are the Armstrong numbers.
"""

def q13():
    x = int(input("Enter start: "))
    y = int(input("Enter End: "))
    for i in range(x,y+1):
        digit = []
        og = i
        num = 0
        while i!=0 :
            digit.append(i%10)
            i = i//10
        for i in digit :
            num += i**len(digit)
        if(og==num):
            print(num,end=',')

q13()

# Write code here

"""###`Problem 14`:Calculate the angle between the hour hand and minute hand.

Note: There can be two angles between hands; we need to print a minimum of two. Also, we need to print the floor of the final result angle. For example, if the final angle is 10.61, we need to print 10.

Input:<br>
H = 9 , M = 0<br>
Output:<br>
90<br>
Explanation:<br>
The minimum angle between hour and minute
hand when the time is 9 is 90 degress.
"""

def q14():
    # hour hand -> 12 optns -> 30deg
    # minute hand -> 60 optns -> 6deg 
    # i can take a reference point say 12 = H or 0 = M and then cal , each hand's angle , then subtract . 

    H = int(input("Enter Hour : "))
    M = int(input("Enter minute : "))
    if (H < 0 or M < 0 or H > 12 or M > 60):
        print('Wrong input')
        return 0
    # every hour point yeilds to 30degree-- 12 hours-360degree plus if minute hand moves hour hands move too
# Every minute after hour hand take 0.5 degree movement. clockwise

    h_ang = H*30 + M*0.5
    m_ang = M*6
    ang = abs(h_ang - m_ang)
    if(ang < (360 - ang)):
        print("angle =",int(ang))
    else:
        print("angle =",360-int(ang))

# Write code here

"""###`Problem 15`:Given two rectangles, find if the given two rectangles overlap or not. A rectangle is denoted by providing the x and y coordinates of two points: the left top corner and the right bottom corner of the rectangle. Two rectangles sharing a side are considered overlapping. (L1 and R1 are the extreme points of the first rectangle and L2 and R2 are the extreme points of the second rectangle).

Note: It may be assumed that the rectangles are parallel to the coordinate axis.

<img src='https://www:.geeksforgeeks.org/wp-content/uploads/rectanglesOverlap.png' width='300' height='200'>
"""
def q15():
    print("Rectangle 1 ")
    xl1 = int(input("Enter x xoordinate of top left corner of rectangle 1: "))
    yl1 = int(input("Enter y xoordinate of top left corner of rectangle 1: "))
    xr1 = int(input("Enter x xoordinate of bottom right corner of rectangle 1: "))
    yr1 = int(input("Enter y xoordinate of bottom right corner of rectangle 1: "))

    print("Rectangle 2 ")
    xl2 = int(input("Enter x xoordinate of top left corner of rectangle 2: "))
    yl2 = int(input("Enter y xoordinate of top left corner of rectangle 2: "))
    xr2 = int(input("Enter x xoordinate of bottom right corner of rectangle 2: "))
    yr2 = int(input("Enter y xoordinate of bottom right corner of rectangle 2: "))
    
    print("\n")
    if(yr1<yl2<yl1 or yr1<yr2<yl1 or xl1<xl2<xr1 or xl1<xr2<xr1):
        print("OVERLAP")
    else:
        print("No OVERLAP")

# Write code here